/*
 * This source file was generated by the Gradle 'init' task
 */
package cs1530.dbdemo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appUnitTest() {
        App classUnderTest = new App();
        assertTrue(true, "This directory could hold tests such as JUnit tests. See CS 1632.");
    }
}
